/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const BlogIndexLazyRouteImport = createFileRoute('/blog/')()
const BlogArticleIdLazyRouteImport = createFileRoute('/blog/$articleId')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const BlogIndexLazyRoute = BlogIndexLazyRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blog/index.lazy').then((d) => d.Route))
const BlogArticleIdLazyRoute = BlogArticleIdLazyRouteImport.update({
  id: '/blog/$articleId',
  path: '/blog/$articleId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/blog/$articleId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/blog/$articleId': typeof BlogArticleIdLazyRoute
  '/blog/': typeof BlogIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/blog/$articleId': typeof BlogArticleIdLazyRoute
  '/blog': typeof BlogIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/blog/$articleId': typeof BlogArticleIdLazyRoute
  '/blog/': typeof BlogIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog/$articleId' | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/$articleId' | '/blog'
  id: '__root__' | '/' | '/blog/$articleId' | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BlogArticleIdLazyRoute: typeof BlogArticleIdLazyRoute
  BlogIndexLazyRoute: typeof BlogIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$articleId': {
      id: '/blog/$articleId'
      path: '/blog/$articleId'
      fullPath: '/blog/$articleId'
      preLoaderRoute: typeof BlogArticleIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BlogArticleIdLazyRoute: BlogArticleIdLazyRoute,
  BlogIndexLazyRoute: BlogIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
